replicaCount: 2

image:
  repository: parkkyungtae/kub-first-app
  pullPolicy: Always
  tag: "1"

resources:
  limits:
    cpu: "200m"
    memory: "200Mi"
  requests:
    cpu: "100m"
    memory: "100Mi"

hpa:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  stabilizationWindowSeconds: 60